services:
  udmf-www:
    build:
      context: ./www
      dockerfile: Dockerfile
    container_name: udmf_www
    restart: always
    networks:
      - udmf_network
      - traefik_network
    labels:
      - "traefik.enable=true"
      # Dev - udmf.yrx.cz
      - "traefik.http.routers.udmf-www.rule=Host(`udmf.yrx.cz`)"
      - "traefik.http.routers.udmf-www.entrypoints=websecure"
      - "traefik.http.routers.udmf-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.udmf-www.service=udmf-www-service"
      # Service
      - "traefik.http.services.udmf-www-service.loadbalancer.server.port=80"

  udmf-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: udmf_api
    restart: always
    volumes:
      - ./backend/feedback:/app/feedback
    networks:
      - udmf_network
      - traefik_network
    labels:
      - "traefik.enable=true"
      # API - api-udmf.yrx.cz
      - "traefik.http.routers.udmf-api.rule=Host(`api-udmf.yrx.cz`)"
      - "traefik.http.routers.udmf-api.entrypoints=websecure"
      - "traefik.http.routers.udmf-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.udmf-api.service=udmf-api-service"
      # Service
      - "traefik.http.services.udmf-api-service.loadbalancer.server.port=3001"

networks:
  udmf_network:
    driver: bridge
  traefik_network:
    external: true
